Эндпоинты для ИПР.
pashpiter/Hackathon_Alfa_task pull request #24
Opened 2024-01-30 00:57 UTC by ivnpvl

Запросы прогонял, живое. ).

2024-01-30 09:43 UTC, dcomrad requested changes

2024-01-30 09:43 UTC, dcomrad commented on app/db/crud/base.py
> +        return db_objs.unique().scalars().all()
Этот метод является базовым и используется всеми разработчиками в команде. На мой взгляд, изменение поведение метода, который затрагивает всех, необходимо делать через обсуждение, чтобы была уверенность, что ничего не сломается. 
Можно пойти другим путём:
1. добавить в функцию keyword аргумент `unique: bool = False`. Так не сломаются текущие вызовы (сохранится обратная совместимость) и ты добьешся необходимого функционала.
2. написать необходимый метод в классе-наследнике (CRUDPlan)

2024-01-30 09:43 UTC, dcomrad commented on app/schemas/user.py
> +    plan: Optional["Plan"] = Relationship(back_populates="employee")
Аналогично предыдущему комметарию - изменения в код, затрагивающие остальных. UserBase и его наследник UserRead ужё используется мной в комментариях и мне план сотрудника, написавшего комментарий, не нужен. Во-первых, это лишние данные, которые нужно передавать по сети. Во-вторых, это ещё один запрос в базу.

2024-01-30 18:07 UTC, pashpiter commented on app/api/v1/endpoints/plan.py
> +    validators.check_supervisor_role(user)
await

2024-01-30 18:09 UTC, ivnpvl commented on app/api/v1/endpoints/plan.py
> +    validators.check_supervisor_role(user)
Зачем, это обычная функция, запросы к БД не делает, просто проверяет поле.

2024-01-31 02:36 UTC, pashpiter approved these changes
Пара исправлений

2024-01-31 02:36 UTC, pashpiter commented on app/schemas/plan.py
> +    tasks: List[TaskRead] = []
тут может быть None
tasks: List[TaskRead] | None = []

2024-01-31 02:36 UTC, pashpiter commented on app/schemas/plan.py
> +    aim_description: str
ДУмаю что дату у ИПР можно изменять
Добавишь expired_at
И тут стоит указать значения по умолчанию (None)

2024-01-31 02:39 UTC, pashpiter commented on app/api/v1/endpoints/plan.py
> +    validators.check_supervisor_role(user)
Короче, лучше это делать в async режиме (на мой взгляд), понятно что там временные затраты будут минимальны, но все равно. У нас вроде асинхронное приложение)
Тут прикол не в том что внутри есть async (await) а просто что приложение асинхронное)

Это мой взгляд)

2024-01-31 22:52 UTC, dcomrad approved these changes

2024-01-31 23:14 UTC, merged