Поле для photo в User, StaticFiles, редактирование Tasks
pashpiter/Hackathon_Alfa_task pull request #25
Opened 2024-01-30 21:47 UTC by pashpiter

Добавлено поле photo для User
Статика 
Отредактированы схемы и эндпоинты для задач

2024-01-31 11:32 UTC, ivnpvl requested changes

2024-01-31 11:32 UTC, ivnpvl commented on app/api/v1/endpoints/employee.py
> +    await validators.check_role(user)
Из ТЗ непонятно:
- может ли сотрудник запрашивать информацию о себе,
- руководитель может смотреть только своих сотрудников или вообще всех.

2024-01-31 11:32 UTC, ivnpvl commented on app/api/v1/validators.py
>  async def check_plan_and_user_access(
Это сломает код в моей ветке, я использую это для валидации именно по plan_id.
Ок, могу написать себе отдельный валидатор.

2024-01-31 11:32 UTC, ivnpvl commented on app/core/config.py
> +        os.makedirs(STATIC_DIR, exist_ok=True)
Директории можно создавать через pathlib, тогда не придётся импотрировать os.

2024-01-31 11:32 UTC, ivnpvl commented on app/db/crud/task.py
> +            self,
У себя в ветке я добавлял параметр unique в CRUDBase.get_all, может остановиться на этом варианте, потому что и в тасках и в планах это нужно.
Подозреваю, что у тебя CRUDTask.update_all тоже должен быть с параметром unique.

2024-01-31 11:32 UTC, ivnpvl commented on app/schemas/comment.py
> +    from .task import Task
Вроде нигде не используется.

2024-01-31 11:32 UTC, ivnpvl commented on app/schemas/task.py
> +    plan_id: Optional[PK_TYPE] = Field(foreign_key="plan.id")
plan_id у нас не Optional, он всегда же есть.
А комментариев как раз может не быть.

2024-01-31 11:32 UTC, ivnpvl commented on app/schemas/task.py
> +    expires_at: Optional[date] = None
Можно валидацию даты запихать в отдельный класс, посмотри в моей ветке.
DRY, т.к. используется в четырёх местах: создание и обновление - плана и задачи.

2024-01-31 16:21 UTC, pashpiter commented on app/api/v1/endpoints/employee.py
> +    await validators.check_role(user)
employee только для руководителя

2024-01-31 16:22 UTC, pashpiter commented on app/api/v1/validators.py
>  async def check_plan_and_user_access(
Короче я ошибся в url и поэтому у меня только так проверка может быть-__-

2024-01-31 16:30 UTC, pashpiter commented on app/db/crud/task.py
> +            self,
У меня просто нет пока этих изменений) а так да, можно сделать в get_all unique

2024-01-31 16:31 UTC, pashpiter commented on app/schemas/comment.py
> +    from .task import Task
Спасибо

2024-01-31 16:32 UTC, pashpiter commented on app/schemas/task.py
> +    plan_id: Optional[PK_TYPE] = Field(foreign_key="plan.id")
ДУмаю что лучше написать optional, чтобы было меньше проблем
Тут ведь тоже мы указываем)
```id: Optional[PK_TYPE] = Field(default=None, primary_key=True)```

2024-01-31 16:33 UTC, pashpiter commented on app/schemas/task.py
> +    expires_at: Optional[date] = None
Потом это изменю из dev
Я так понял, тогда валидацию вообще нигде для expires_at. не нужно писать?

2024-01-31 16:59 UTC, pashpiter commented on app/core/config.py
> +        os.makedirs(STATIC_DIR, exist_ok=True)
Вот это не понял) 
pathlib импортировать не нужно?)

2024-01-31 17:20 UTC, ivnpvl commented on app/core/config.py
> +        os.makedirs(STATIC_DIR, exist_ok=True)
Мы изначально использовали pathlib.Path для хранения и доступа к путям.
Все директории у нас являются объектами класса Path. У Path есть готовые методы работы с путями.
То есть использовать пакет os не имеет смысла, всё, что нужно, есть в Path.
Просто:
LOG_DIR.mkdir(exists_ok=True)
итд.

2024-01-31 17:22 UTC, ivnpvl commented on app/schemas/task.py
> +    plan_id: Optional[PK_TYPE] = Field(foreign_key="plan.id")
В id, как я понимаю, проблема в том, что его изначально нет (он как бы None), но он автогенерируется после валидации pydantic.
А plan_id есть всегда.

2024-01-31 17:26 UTC, ivnpvl commented on app/schemas/task.py
> +    expires_at: Optional[date] = None
Да. Annotetad - это валидация не только типа, но и кастомных требований к значению. Если таких (одинаковых) полей много, то имеет смысл один раз объединить их тип через Annotated.

2024-01-31 17:40 UTC, ivnpvl commented on app/core/config.py
> +        os.makedirs(STATIC_DIR, exist_ok=True)
В джанге до определённой версии в сеттингс используется os, в последних pathlib.
os - это большая либа для всего, в т.ч. для работы с путями.
pathlib - либа только для работы с путями.
То есть по-хорошему: или - или.
Плюсом pathlib является то, что там всё сделано в ООП стиле, есть класс пути и ним можно делать всякое (Path.parent, Path.mkdir(), итд.) и выглядит лаконичнее, чем через os.
Мощная штука крч, рекомендую.
).
https://docs.python.org/3/library/pathlib.html

2024-01-31 23:00 UTC, dcomrad commented on app/schemas/task.py
> +    plan_id: Optional[PK_TYPE] = Field(foreign_key="plan.id")
Да, похоже, что так и есть - plan_id есть всегда, значит можно не делать его Optional

2024-01-31 23:03 UTC, dcomrad commented
@pashpiter статику не нужно через FastAPI прикручивать, если у нас nginx есть. Мы вчера общались и я обещал сделать статику. Завтра утром настрою nginx. Убери из своего ПР, пожалуйста, всё что связано со статикой

2024-01-31 23:03 UTC, dcomrad commented on app/core/config.py
> +        os.makedirs(STATIC_DIR, exist_ok=True)
Я поправлю

2024-01-31 23:05 UTC, dcomrad commented
В коммит попал файл .DS_Store. Надо бы его в гитигнор добавить

2024-01-31 23:08 UTC, pashpiter commented on app/core/config.py
> +        os.makedirs(STATIC_DIR, exist_ok=True)
уже поправил) Сейчас коммит сделаю

2024-02-01 00:11 UTC, pashpiter commented on app/schemas/task.py
> +    expires_at: Optional[date] = None
Поправил

2024-02-01 07:48 UTC, ivnpvl approved these changes
Отлично.

2024-02-01 07:50 UTC, merged