Добавил эндпоинт получения непрочитанных комментариев
pashpiter/Hackathon_Alfa_task pull request #41
Opened 2024-02-01 19:36 UTC by dcomrad

2024-02-01 19:39 UTC, dcomrad commented on app/api/v1/endpoints/comment.py
> +    response_model=int,
Возвращается просто число - количество непрочитанных комментариев

2024-02-01 19:40 UTC, dcomrad commented on app/api/v1/endpoints/task.py
> +    task = await validators.check_task_and_user_access(
Т.к. мне тоже потребовалась задача после валидации, я поменял сигнатуру функции-валидатора. Теперь она возвращает задачу.

2024-02-01 19:42 UTC, dcomrad commented on app/db/crud/base.py
> +    ) -> None:
Получилось оптимизировать метод удаления, чтобы он не делал два запроса к базе (select -> delete).
Однако теперь метод ничего не возвращает. Я проверил по коду, что никто не использует результат работы метода, поэтому позволил себе поменять сигнатуру.

2024-02-01 21:05 UTC, ivnpvl requested changes

2024-02-01 21:05 UTC, ivnpvl commented on app/db/crud/comment.py
> +        await unread_comment_crud.delete(
Получается, что класс зависит от объекта другого класса. Лучше эту логику вынести в эндпоинты.

2024-02-01 23:01 UTC, dcomrad commented on app/db/crud/comment.py
> +        await unread_comment_crud.delete(
Согласен, некрасиво получилось. Поправил.

2024-02-02 02:00 UTC, pashpiter approved these changes

2024-02-02 09:37 UTC, dcomrad commented
@ivnpvl не могу смержить без твоего апрува. Сделай, пожалуйста

2024-02-02 10:31 UTC, ivnpvl approved these changes

2024-02-02 10:35 UTC, merged