Добавил автоматическую проверку статусов, пара валидаторов, и исправления в POST PATCH задач
pashpiter/Hackathon_Alfa_task pull request #43
Opened 2024-02-02 05:31 UTC by pashpiter

check_plan_tasks_expired_date вроде никто не использовал, изменил там plan_id на PLAN
в check_plan_and_user_access был неверно указан параметр _task_id_, изменен на plan_id
Еще новый модуль в req -> aiocron

2024-02-02 10:21 UTC, dcomrad commented on app/services/daily_status_check.py
> +        print(5555)
.

2024-02-02 10:21 UTC, dcomrad commented on app/services/daily_status_check.py
> +    на FAILD. После этого все статусы задач CREATED и IN_PROGRESS в изменных
FAILED

2024-02-02 10:21 UTC, dcomrad commented on app/services/daily_status_check.py
> +                    RETURNING plans.task.id;"""
А зачем returning, если результат работы запроса далее не используется?

2024-02-02 10:21 UTC, dcomrad commented on app/api/v1/validators.py
> +async def check_task_input_same_status(
Я не вижу проблемы в том, что произойдёт смена статуса сама на себя. Т.е. я не считаю, что в этом случае нужно кидать исключение. Бывает так, что пользователь начал редактировать что-то, потом передумал и вместо отмены, нажал сохранить. Строго говоря это не является ошибкой работы программы или ошибкой ввода. Предлагаю на такие случаи не реагировать.

2024-02-02 10:21 UTC, dcomrad commented on app/api/v1/endpoints/task.py
> +    # Проверка что все задачи имею статус DONE
Похоже, что комментарий сбивает с толку. Т.к. в строке 143 есть ещё один комментарий, я интуитивно отношу первый к строкам 139-142, но тут нет никакой проверки.

2024-02-02 10:21 UTC, dcomrad commented on app/api/v1/endpoints/task.py
> +    if tasks_not_done.count(lambda x: x.status != TaskStatus.DONE):
Как я понял, идея состоит в том, что если после обновления задачи все остальные имеют статус DONE, то можно помечать весь план целиком, как DONE. Если всё так, то есть несколько рекомендаций:
1. Сразу делать выборку задач, имеющих статус не DONE
2. Делать всю эту проверку только в том случае, если прилетел апдейт статуса задачи на DONE.

2024-02-02 10:21 UTC, dcomrad commented on app/api/v1/endpoints/plan.py
> +        await validators.check_new_date_gt_current(
Функция check_plan_and_user_access возвращает объект класса Plan. Можно передать его в эту функцию проверки времени, чтобы внутри неё снова не получать из базы ИПР по d

2024-02-02 10:21 UTC, dcomrad commented on app/api/v1/validators.py
> +async def check_new_date_gt_current(
Нарушение принципа DRY - эти две функции делают одно и то же. Я бы сделал общую, принимающую Task | Plan.

2024-02-02 10:21 UTC, dcomrad commented on app/api/v1/validators.py
> +        session: AsyncSession
session не используется внутри функции

2024-02-02 10:31 UTC, dcomrad commented
Почитал про библиотеку aiocron. Смешанные чувства.

Последний релиз в 2021 году, т.е. библиотека больше не поддерживается
https://pypi.org/project/aiocron/

317 звёзд и 20 форков на Гитхабе, что довольно мало.
![image](https://github.com/pashpiter/Hackathon_Alfa_task/assets/58635519/464f5426-8ccc-4e46-9ae1-b373ffe61896)

Висит 6 открытых [Issues](https://github.com/gawel/aiocron/issues), некоторые из которых:
- Crontab stopped running #34
- DST causing tasks to run twice #28
что выглядит не очень надёжно

Я бы не стал использовать такую библиотеку в работе реального проекта, особенно на таком ответственном участке.

Для подобных задач есть стандарт де-факто - Celery

2024-02-02 10:52 UTC, ivnpvl commented on app/api/v1/endpoints/plan.py
> +        await validators.check_new_date_gt_current(
Это у меня, поменяю в своей ветке, пока не залили.

2024-02-02 14:06 UTC, pashpiter commented on app/api/v1/endpoints/task.py
> +    if tasks_not_done.count(lambda x: x.status != TaskStatus.DONE):
Если сделать запрос с задачами DONE, то я не узнаю есть ли там задачи с другими статусами

2024-02-02 15:22 UTC, dcomrad commented on app/api/v1/endpoints/task.py
> +    if tasks_not_done.count(lambda x: x.status != TaskStatus.DONE):
Ок, тогда я неправильно интерпретировал написанное.

2024-02-02 22:11 UTC, pashpiter commented
Убрал aiocrion, сделал с помощью aiosync.sleep()

2024-02-03 08:22 UTC, ivnpvl requested changes
Сначала посмотрел новый ПР и комментарии по логике написал там.
(.

2024-02-03 12:06 UTC, dcomrad approved these changes

2024-02-03 12:06 UTC, dcomrad commented on app/api/v1/validators.py
>      return task
return можно убрать

2024-02-03 12:25 UTC, ivnpvl approved these changes

2024-02-03 12:27 UTC, ivnpvl commented
Здесь тогда апрув, исправления смотри в следующем ПР.

2024-02-03 15:27 UTC, merged