Уведомления для задач, NotificationsHeader, create_many notif* crud
pashpiter/Hackathon_Alfa_task pull request #45
Opened 2024-02-03 04:42 UTC by pashpiter

Добавление уведомлений при изменении статусов задач.
@dcomrad глянь статусы для NotificationsHeader и функцию для сжатия имени.

2024-02-03 07:28 UTC, ivnpvl requested changes

2024-02-03 07:28 UTC, ivnpvl commented on app/api/v1/endpoints/task.py
>          )
Наверное лучше в task явно получать одну таску task = await task_crud.update(...)[0].

2024-02-03 07:28 UTC, ivnpvl commented on app/api/v1/endpoints/task.py
> +        if tasks_not_done.count(lambda x: x.status != TaskStatus.DONE):
Это не должно работать, count проверяет значение, а не вызывает функцию, количество лямбда-функций в списке тасок - ноль, т.е. тут всегда будет ноль.
Предлагаю использовать filter или all-any.

2024-02-03 07:28 UTC, ivnpvl commented on app/api/v1/endpoints/task.py
>      )
Аналогично, тут мы ожидаем одну таску, исходя из названия переменной.

2024-02-03 07:28 UTC, ivnpvl commented on app/api/v1/endpoints/task.py
> +
Три запроса с одинаковой логикой, может лучше объединить?
```
TASK_NOTIFICATION: dict = {
    TaskStatus.Done: {
        "type": NotificationType.SUCCESS,
        "header": NotificationHeader.TASK_DONE,
    },
    ...
}

if task_patch.status in TASK_NOTIFICATION:
    await notification_crud.create(
        session, {
            "recipient_id": task.plan.employee_id,
            "task_id": task.id,
            "content": "{} {}".format(
                name_compression(task.plan.employee.full_name), task.name,
            ),
            **TASK_NOTIFICATION[task_plan.status]
        }
    )
```

2024-02-03 07:28 UTC, ivnpvl commented on app/api/v1/validators.py
> +    return task
До этого return никогда не дойдёт, все подходящие условия проходят в return выше.

2024-02-03 07:28 UTC, ivnpvl commented on app/api/v1/validators.py
> +    return plan
Аналогично функции выше.

2024-02-03 07:28 UTC, ivnpvl commented on app/core/utils.py
> +def name_compression(full_name: str) -> str:
Я бы вообще от этого отказался. Экономия по памяти минимальная, потенциально ломает сервер.
У нас по ТЗ не гарантировано, что имена будут формата "{фамилия} {имя} {отчество}". 
Даже в паспорте РФ может не быть отчества в силу национальных особенностей.
Если о-о-очень хочется это использовать, надо split завернуть в try-except блок.

2024-02-03 07:28 UTC, ivnpvl commented on app/core/utils.py
> +    return f"{split_name[0]} {split_name[1][1]}. {split_name[2][1]}."
Инициалы по индексу 0. ).

2024-02-03 12:08 UTC, dcomrad commented on app/api/v1/endpoints/task.py
>          )
Если получать сразу, то синтаксис вот такой:
`task = (await task_crud.update(...))[0]`

2024-02-03 12:25 UTC, dcomrad commented on app/schemas/notification.py
> +class NotificationHeader(str, enum.Enum):
По этому поводу написал тебе в личные сообщения. Продублирую тут.

Можно, но зачем?
Функционально, заголовок уведомления не накладывает на работу программы никаких ограничений (не так, как статусы, которые участвуют в бизнес-логике)

Из плюсов вижу только то, что фронт не сможет прислать произвольный заголовок, но это же является минусом, т.к. добавление нового заголовка будет возможность только через редактирование кода бэкенда.

Вдобавок к этому, если этот Enum использовать на уровне postgres, как у нас сделано с другими, то придётся делать какой-то словарь, отображающий имя перечисления в человекочитаемое сообщение (task_done = Задача выполнена), т.к. postgres явно не позволит использовать кириллицу с пробелами в качестве значений типа. В общем, небольшая заморочка с неясной выгодой.

Мне кажется, стандартизация типа сообщения уже достаточное ограничение, а текст может быть любым - пусть фронт упражняется со словарями и прочим.

2024-02-03 12:25 UTC, dcomrad commented on app/core/utils.py
> +def name_compression(full_name: str) -> str:
Это нужно для комментариев - там видите ли используется сокращённый формат имени)
В идеале, конечно, для таких вещей нужно создавать отдельные поля в БД, чтобы стандартизировать расположение ФИО. Но в нашем случае это всё избыточно и подобная функция будет нелишней (раз так требуется с точки зрения дизайна). Другой вопрос, как указал @ivnpvl надо сделать код безопасным.

Давай я займусь этим. Сделаю `@property` метод на уровне схемы пользователя

2024-02-03 12:25 UTC, dcomrad commented on app/core/utils.py
> +    return f"{split_name[0]} {split_name[1][1]}. {split_name[2][1]}."
Код упадёт, если full_name не будет состоять из трёх слов.
@pashpiter чё-то на тебе слишком много всего) как написал выше, я сделаю.

2024-02-03 13:16 UTC, dcomrad commented on app/core/utils.py
> +def name_compression(full_name: str) -> str:
Сделал в отдельной ветке. Создал ПР

2024-02-03 14:56 UTC, dcomrad commented on app/schemas/notification.py
> +class NotificationHeader(str, enum.Enum):
Галя, у нас отмена.
Стормозил, забыв о том, что уведомления мы формируем на стороне бэка. В таком случае, какой-то словарь или перечисления оправданны.

2024-02-03 14:59 UTC, dcomrad commented on app/schemas/notification.py
> +    FILE_ATTACHMENT = "Прикреплен файл"
Кажется, что указание какой конкретно тип комментария добавлен, это лишнее. Комментарий и ладно.

2024-02-03 15:00 UTC, dcomrad commented on app/schemas/notification.py
> +    COMMENT_NEW = "Добавлен комментарий"
По-моему, более естественно звучит "Новый комментарий"

2024-02-04 00:56 UTC, dcomrad commented on app/core/utils.py
> +def name_compression(full_name: str) -> str:
Разве эту функцию не нужно удалить? Я же сделал поле short_name у пользователя

2024-02-04 01:12 UTC, dcomrad approved these changes

2024-02-04 01:12 UTC, dcomrad commented on app/db/crud/task.py
> +    async def update_many(
Я бы поменял имя на что-то типа update_by_ids, т.к. у класса есть метод update, а значит update_many читается, как обновление нескольких записей, но фактически update тоже обновляет несколько записей

2024-02-04 01:12 UTC, dcomrad commented on app/schemas/notification.py
> +    FILE_ATTACHMENT = "Прикреплен файл"
Прикрепление файла и ссылки я удалил. Как я понял, ты не возражал

2024-02-04 10:42 UTC, ivnpvl approved these changes

2024-02-04 14:47 UTC, merged